version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg-local
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: paper
      POSTGRES_PASSWORD: paper1234
      POSTGRES_DB: paper_local
    volumes:
      - pg_local_data:/var/lib/postgresql/data

volumes:
  pg_local_data:

