logging:
  level:
    swyp.paperdot.translator: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# GPT-5 mini 연동을 위한 OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY} # .env 파일이나 환경 변수에서 값을 읽어옵니다.
    #model: "gpt-3.5-turbo-1106"
    model: "gpt-5-mini" # 사용할 LLM 모델입니다.
    url: "https://api.openai.com/v1/chat/completions" # OpenAI 채팅 완료를 위한 엔드포인트입니다.





# 시스템 메시지 설정
openai.api.system-message: '당신은 문서 요약을 전문으로 하는 유용한 어시스턴트입니다.  '

ncp:
  storage:
    region: ${NCP_REGION}
    endpoint: ${NCP_ENDPOINT}
    accessKey: ${NCP_ACCESS_KEY}
    secretKey: ${NCP_SECRET_KEY}
    bucket: ${NCP_BUCKET}